# Generated by Django 5.1.6 on 2025-02-26 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('budgetid', models.AutoField(db_column='BudgetID', primary_key=True, serialize=False)),
                ('totalamount', models.FloatField(db_column='TotalAmount')),
            ],
            options={
                'db_table': 'Budget',
            },
        ),
        migrations.CreateModel(
            name='Finishedgoods',
            fields=[
                ('productid', models.AutoField(db_column='ProductID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('unit_price', models.FloatField(db_column='UnitPrice')),
                ('quantity', models.FloatField(db_column='Quantity')),
                ('totalamount', models.FloatField(db_column='TotalAmount')),
            ],
            options={
                'db_table': 'FinishedGoods',
            },
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('positionid', models.AutoField(db_column='PositionID', primary_key=True, serialize=False)),
                ('positionname', models.CharField(db_column='PositionName', max_length=50)),
            ],
            options={
                'db_table': 'Positions',
            },
        ),
        migrations.CreateModel(
            name='Rawmaterials',
            fields=[
                ('rawmaterialid', models.AutoField(db_column='RawMaterialID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('unit_price', models.FloatField(db_column='UnitPrice')),
                ('quantity', models.FloatField(db_column='Quantity')),
                ('totalamount', models.FloatField(db_column='TotalAmount')),
            ],
            options={
                'db_table': 'RawMaterials',
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('unitid', models.AutoField(db_column='UnitID', primary_key=True, serialize=False)),
                ('unitname', models.CharField(db_column='UnitName', max_length=50)),
            ],
            options={
                'db_table': 'Units',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employeeid', models.AutoField(db_column='EmployeeID', primary_key=True, serialize=False)),
                ('fullname', models.CharField(db_column='FullName', max_length=100)),
                ('salary', models.FloatField(db_column='Salary')),
                ('address', models.CharField(blank=True, db_column='Address', max_length=200, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=20, null=True)),
                ('positionid', models.ForeignKey(db_column='PositionID', on_delete=django.db.models.deletion.CASCADE, to='myapp.positions')),
            ],
            options={
                'db_table': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Productproduction',
            fields=[
                ('productionid', models.AutoField(db_column='ProductionID', primary_key=True, serialize=False)),
                ('quantity', models.FloatField(db_column='Quantity')),
                ('productiondate', models.DateField(db_column='ProductionDate')),
                ('employeeid', models.ForeignKey(db_column='EmployeeID', on_delete=django.db.models.deletion.CASCADE, to='myapp.employees')),
                ('productid', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, to='myapp.finishedgoods')),
            ],
            options={
                'db_table': 'ProductProduction',
            },
        ),
        migrations.CreateModel(
            name='Productsales',
            fields=[
                ('saleid', models.AutoField(db_column='SaleID', primary_key=True, serialize=False)),
                ('quantity', models.FloatField(db_column='Quantity')),
                ('totalamount', models.FloatField(db_column='TotalAmount')),
                ('saledate', models.DateField(db_column='SaleDate')),
                ('employeeid', models.ForeignKey(db_column='EmployeeID', on_delete=django.db.models.deletion.CASCADE, to='myapp.employees')),
                ('productid', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, to='myapp.finishedgoods')),
            ],
            options={
                'db_table': 'ProductSales',
            },
        ),
        migrations.CreateModel(
            name='Rawmaterialpurchases',
            fields=[
                ('purchaseid', models.AutoField(db_column='PurchaseID', primary_key=True, serialize=False)),
                ('quantity', models.FloatField(db_column='Quantity')),
                ('totalamount', models.FloatField(db_column='TotalAmount')),
                ('purchasedate', models.DateField(db_column='PurchaseDate')),
                ('employeeid', models.ForeignKey(db_column='EmployeeID', on_delete=django.db.models.deletion.CASCADE, to='myapp.employees')),
                ('rawmaterialid', models.ForeignKey(db_column='RawMaterialID', on_delete=django.db.models.deletion.CASCADE, to='myapp.rawmaterials')),
            ],
            options={
                'db_table': 'RawMaterialPurchases',
            },
        ),
        migrations.AddField(
            model_name='rawmaterials',
            name='unitid',
            field=models.ForeignKey(db_column='UnitID', on_delete=django.db.models.deletion.CASCADE, to='myapp.units'),
        ),
        migrations.AddField(
            model_name='finishedgoods',
            name='unitid',
            field=models.ForeignKey(db_column='UnitID', on_delete=django.db.models.deletion.CASCADE, to='myapp.units'),
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('ingredientid', models.AutoField(db_column='IngredientID', primary_key=True, serialize=False)),
                ('quantity', models.FloatField(db_column='Quantity')),
                ('productid', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, to='myapp.finishedgoods')),
                ('rawmaterialid', models.ForeignKey(db_column='RawMaterialID', on_delete=django.db.models.deletion.CASCADE, to='myapp.rawmaterials')),
            ],
            options={
                'db_table': 'Ingredients',
                'unique_together': {('productid', 'rawmaterialid')},
            },
        ),
    ]
